/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.proteus.la;

import static com.proteus.la.MessageUtils.getMessage;

public class App {
    public static void main(String[] args) {
        System.out.println(getMessage());
    }
}
